language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
before_install:
  - "gem install bundler -v '~> 1.10'"
bundler_args: "--jobs=2"
cache: bundler
script:
  - "bundle exec rspec"
